# -*- coding: utf-8 -*-
"""part3_api_files

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qz8lL0kZS-H36lh1NZs3pF-T79opcqsn
"""

# STEP 1: Writing to file

# opening file in write mode
file = open("python_notes.txt", "w", encoding="utf-8")

# writing basic topics
file.write("Topic 1: Variables store data. Python is dynamically typed.\n")
file.write("Topic 2: Lists are ordered and mutable.\n")
file.write("Topic 3: Dictionaries store key-value pairs.\n")
file.write("Topic 4: Loops automate repetitive tasks.\n")
file.write("Topic 5: Exception handling prevents crashes.\n")

file.close()

print("File written successfully.")

# STEP 2: Append more content

file = open("python_notes.txt", "a", encoding="utf-8")

# adding my own lines
file.write("Topic 6: Functions help reuse code.\n")
file.write("Topic 7: APIs allow communication between systems.\n")

file.close()

print("Lines appended successfully.")

# STEP 3: Reading file and printing with numbers

file = open("python_notes.txt", "r", encoding="utf-8")

lines = file.readlines()   # read all lines

file.close()

# printing lines with numbering
count = 0
for line in lines:
    count += 1
    print(f"{count}. {line.strip()}")   # strip removes \n

print("Total lines:", count)

# STEP 4: Search keyword in file

keyword = input("Enter a keyword to search: ").lower()

found = False

for line in lines:
    if keyword in line.lower():   # case-insensitive match
        print(line.strip())
        found = True

if not found:
    print("No matching lines found.")

!pip install requests

import requests

# STEP 6: Fetch products from API

url = "https://dummyjson.com/products?limit=20"

response = requests.get(url)

data = response.json()   # convert into python dictionary

products = data["products"]

# printing table header
print("ID | Title | Category | Price | Rating")
print("--------------------------------------------")

# loop through products
for item in products:
    print(item["id"], "|", item["title"], "|", item["category"], "|", "$"+str(item["price"]), "|", item["rating"])

# STEP 7: Filter and sort products

filtered_products = []

# filter products with rating >= 4.5
for item in products:
    if item["rating"] >= 4.5:
        filtered_products.append(item)

# sort by price (high to low)
filtered_products.sort(key=lambda x: x["price"], reverse=True)

print("\nFiltered & Sorted Products:\n")

# printing result
for item in filtered_products:
    print(item["title"], "| Price:", item["price"], "| Rating:", item["rating"])

# STEP 8: Fetch laptops category

url = "https://dummyjson.com/products/category/laptops"

response = requests.get(url)

data = response.json()

products = data["products"]

print("\nLaptops List:\n")

for item in products:
    print(item["title"], "| Price:", item["price"])

# STEP 9: POST request (add product)

url = "https://dummyjson.com/products/add"

new_product = {
    "title": "My Custom Product",
    "price": 999,
    "category": "electronics",
    "description": "A product I created via API"
}

response = requests.post(url, json=new_product)

data = response.json()

print("\nPOST Response:\n")
print(data)

# STEP 10: Safe divide function

def safe_divide(a, b):
    try:
        result = a / b
        return result

    except ZeroDivisionError:
        return "Error: Cannot divide by zero"

    except TypeError:
        return "Error: Invalid input types"


# testing
print(safe_divide(10, 2))
print(safe_divide(10, 0))
print(safe_divide("ten", 2))

# STEP 11: Safe file reading

def read_file_safe(filename):
    try:
        file = open(filename, "r", encoding="utf-8")
        content = file.read()
        file.close()
        return content

    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")

    finally:
        print("File operation attempt complete.")


# testing
print(read_file_safe("python_notes.txt"))   # should work
print(read_file_safe("ghost_file.txt"))     # should fail

# STEP 12: API with exception handling

try:
    response = requests.get("https://dummyjson.com/products?limit=5", timeout=5)

    if response.status_code == 200:
        data = response.json()
        print("\nProducts fetched successfully")

    else:
        print("Error: Received status code", response.status_code)

except requests.exceptions.ConnectionError:
    print("Connection failed. Please check your internet.")

except requests.exceptions.Timeout:
    print("Request timed out. Try again later.")

except Exception as e:
    print("Unexpected error:", e)

# STEP 13: Input validation loop

while True:
    user_input = input("\nEnter product ID (1–100) or 'quit': ")

    if user_input.lower() == "quit":
        print("Exiting...")
        break

    # validation
    if not user_input.isdigit():
        print("Invalid input. Please enter a number.")
        continue

    product_id = int(user_input)

    if product_id < 1 or product_id > 100:
        print("Please enter ID between 1 and 100.")
        continue

    # API call
    try:
        url = f"https://dummyjson.com/products/{product_id}"
        response = requests.get(url, timeout=5)

        if response.status_code == 404:
            print("Product not found.")

        elif response.status_code == 200:
            data = response.json()
            print("Title:", data["title"])
            print("Price:", data["price"])

    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")

    except requests.exceptions.Timeout:
        print("Request timed out.")

    except Exception as e:
        print("Error:", e)

# STEP 14: Logging errors

from datetime import datetime

def log_error(function_name, error_message):
    file = open("error_log.txt", "a")

    time_now = datetime.now()

    log = f"[{time_now}] ERROR in {function_name}: {error_message}\n"

    file.write(log)
    file.close()

# STEP 15: Trigger errors intentionally

# 1. Connection Error
try:
    bad_url = "https://this-host-does-not-exist-xyz.com/api"
    requests.get(bad_url, timeout=5)

except Exception as e:
    print("Connection error triggered")
    log_error("fetch_products", str(e))


# 2. HTTP 404 error (manual check)
url = "https://dummyjson.com/products/999"

response = requests.get(url)

if response.status_code != 200:
    print("404 error triggered")
    log_error("lookup_product", f"HTTP {response.status_code} for product ID 999")

# STEP 16: Read and print log file

file = open("error_log.txt", "r")

print("\nError Logs:\n")
print(file.read())

file.close()